// mockContractorData.js - Realistic baseline jobs for Member 3 Field Contractor
// Location: DLF CyberCity & Aralias Smart Township, Sector 54, Gurugram (NCR), India
// 100% Constant & Synchronized with Database-react/seed.sql and backend-react

export const CONTRACTOR_PROFILE = {
  id: 'c0000000-0000-0000-0000-000000000002',
  name: 'Voltech Power & Electrical Systems Ltd.',
  lead: 'Vikram Singh Rathore',
  title: 'Lead Field Project Engineer',
  phone: '+91 97230 11984',
  email: 'vikram.singh@voltechpower.in',
  departments: ['Electrical & Power Distribution', 'Civil Infrastructure & Roads'],
  amcContractId: 'AMC-ELE-2025-03',
  status: 'Active',
  rating: 4.92,
  complianceScore: '98.8%',
  crewsDeployed: 5,
};

export const INITIAL_CONTRACTOR_JOBS = [
  {
    id: 'CMP-2026-0104',
    workOrderId: 'WO-2026-090',
    title: '11kV Transformer Substation Feeder Cable Ground Fault & Sparking',
    category: 'Electrical',
    subCategory: 'Distribution Failure',
    location: {
      sector: 'Sector 54',
      block: 'Block C',
      street: 'Substation Road',
      assetId: 'ELE-SUB-12',
      assetName: 'Feeder Substation 12B',
      landmark: 'Feeder Substation 12B Yard behind Community Hall',
      gps: '28.5372° N, 77.3945° E',
    },
    severity: 'Emergency',
    slaDeadline: new Date(Date.now() + 18 * 3600 * 1000).toISOString(),
    status: 'ASSIGNED',
    description: 'Underground armoured XLPE cable sparking intermittently with smoke emission near the main transformer isolator switch.',
    reportedBy: { name: 'Dr. Arvind Swaminathan', role: 'RWA Secretary' },
    createdAt: new Date(Date.now() - 20 * 3600 * 1000).toISOString(),
    beforePhotos: ['https://images.unsplash.com/photo-1544725176-7c40e5a71c5e?auto=format&fit=crop&w=800&q=80'],
    afterPhotos: [],
    inspection: null,
    estimate: null,
    execution: null,
    rework: null,
  },
  {
    id: 'CMP-2026-0103',
    workOrderId: 'WO-2026-087',
    title: 'Boulevard Roadway Streetlight Junction Box Rewiring',
    category: 'Electrical',
    subCategory: 'Streetlight Failure',
    location: {
      sector: 'Sector 54',
      block: 'Block A',
      street: 'Neem Boulevard',
      assetId: 'ELE-SL-89',
      assetName: 'Solar Streetlight Pole #89',
      landmark: 'Near North Gate Roundabout',
      gps: '28.5340° N, 77.3890° E',
    },
    severity: 'Medium',
    slaDeadline: new Date(Date.now() + 28 * 3600 * 1000).toISOString(),
    status: 'REVISION_REQUESTED',
    description: 'Armoured feeder cable short-circuit inside base inspection hatch causing total circuit trip.',
    reportedBy: { name: 'Dr. Arvind Swaminathan', role: 'RWA Secretary' },
    createdAt: new Date(Date.now() - 36 * 3600 * 1000).toISOString(),
    beforePhotos: ['https://images.unsplash.com/photo-1509114397022-ed747cca3f65?auto=format&fit=crop&w=800&q=80'],
    afterPhotos: [],
    inspection: {
      observedProblem: 'Corroded terminal busbar and insulation breakdown from monsoon water seepage.',
      equipmentCondition: 'Moderate - busbar requires wire brush de-oxidation and 2x gland replacement.',
      requiredWork: 'Re-crimp terminals, replace 5m damaged cable, install IP65 weather seal gland.',
      inspectionPhoto: 'https://images.unsplash.com/photo-1509114397022-ed747cca3f65?auto=format&fit=crop&w=800&q=80',
      remarks: 'Inspected by Vikram Singh Rathore on site. Recommended moisture barrier enclosure.',
      inspectedAt: new Date(Date.now() - 10 * 3600 * 1000).toISOString(),
    },
    estimate: {
      items: [
        { rateCardId: 'RATE-01', service: 'Senior Electrical Technician / Wireman', unit: 'Hour', rate: 500, qty: 4, subtotal: 2000 },
        { rateCardId: 'RATE-02', service: 'General Labour (Semi-Skilled / Safety Assist)', unit: 'Hour', rate: 300, qty: 6, subtotal: 1800 },
        { rateCardId: 'RATE-03', service: 'Armoured 3-Core Copper Cable 16 sq.mm', unit: 'Meter', rate: 150, qty: 15, subtotal: 2250 },
      ],
      total: 6050,
      justification: 'Requires excavation alongside walkway for 15 meters cable trenching.',
      submittedAt: new Date(Date.now() - 8 * 3600 * 1000).toISOString(),
      revisionReason: 'Dept Head note: General labour hours excessive for roadside trench. Reduce labour hours from 6 to 3 as per AMC standard benchmarks.',
      revisionRequestedAt: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
    },
    execution: null,
    rework: null,
  },
  {
    id: 'CMP-2026-0105',
    workOrderId: 'WO-2026-091',
    title: 'Sector 54 Community Center Perimeter Floodlight Failure',
    category: 'Electrical',
    subCategory: 'Floodlight Luminaire',
    location: {
      sector: 'Sector 54',
      block: 'Block D',
      street: 'Clubhouse Road',
      assetId: 'ELE-FL-07',
      assetName: 'Perimeter High-Bay Luminaire 07',
      landmark: 'Opposite Tennis Court North Boundary',
      gps: '28.5365° N, 77.3930° E',
    },
    severity: 'Medium',
    slaDeadline: new Date(Date.now() + 8 * 3600 * 1000).toISOString(),
    status: 'IN_PROGRESS',
    description: 'Two 200W LED floodlights flickering intermittently and finally died during evening hours.',
    reportedBy: { name: 'Dr. Arvind Swaminathan', role: 'RWA Secretary' },
    createdAt: new Date(Date.now() - 50 * 3600 * 1000).toISOString(),
    beforePhotos: ['https://images.unsplash.com/photo-1509114397022-ed747cca3f65?auto=format&fit=crop&w=800&q=80'],
    afterPhotos: [],
    inspection: {
      observedProblem: 'Blown surge capacitor and failed SMPS unit on high-bay bracket.',
      equipmentCondition: 'Severe electrical surge damage.',
      requiredWork: 'Mount scaffolding, replace 200W driver, re-route earthing copper strip.',
      inspectionPhoto: 'https://images.unsplash.com/photo-1509114397022-ed747cca3f65?auto=format&fit=crop&w=800&q=80',
      remarks: 'Safety harness required for 7m pole mounting.',
      inspectedAt: new Date(Date.now() - 16 * 3600 * 1000).toISOString(),
    },
    estimate: {
      items: [
        { rateCardId: 'RATE-01', service: 'Senior Electrical Technician / Wireman', unit: 'Hour', rate: 500, qty: 3, subtotal: 1500 },
        { rateCardId: 'RATE-06', service: 'Streetlight 120W LED Luminaire & Surge Driver Replacement', unit: 'Unit', rate: 1800, qty: 1, subtotal: 1800 },
      ],
      total: 3300,
      status: 'APPROVED',
      approvedAt: new Date(Date.now() - 6 * 3600 * 1000).toISOString(),
    },
    execution: {
      startedAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
      actualLabourDetails: 'Senior technician & assistant deployed with extension ladder and multimeter.',
    },
    rework: null,
  },
  {
    id: 'CMP-2026-0106',
    workOrderId: 'WO-2026-085',
    title: 'Stormwater Gully Chamber De-Silting & Sump Grate Repair',
    category: 'Civil',
    subCategory: 'Drainage Failure',
    location: {
      sector: 'Sector 54',
      block: 'Block B',
      street: 'Pine Street',
      assetId: 'CIV-DR-19',
      assetName: 'Roadway Stormwater Catchment Basin #19',
      landmark: 'Next to Block B Nursery School',
      gps: '28.5350° N, 77.3905° E',
    },
    severity: 'High',
    slaDeadline: new Date(Date.now() + 5 * 3600 * 1000).toISOString(),
    status: 'DISPUTED',
    description: 'Gully chamber overflowing with sludge and causing water accumulation during drizzle.',
    reportedBy: { name: 'Dr. Arvind Swaminathan', role: 'RWA Secretary' },
    createdAt: new Date(Date.now() - 40 * 3600 * 1000).toISOString(),
    beforePhotos: ['https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=800&q=80'],
    afterPhotos: ['https://images.unsplash.com/photo-1578662996442-48f60103fc96?auto=format&fit=crop&w=800&q=80'],
    dispute: {
      reason: 'Incomplete silt extraction and debris left on sidewalk',
      remarks: 'Contractor cleared top 6 inches of mud but the 12-inch connecting drain line remains 80% choked with hardened sand. Water pooled immediately after 20 mins of rain. Sidewalk also littered with sludge.',
      disputedAt: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
      disputedBy: 'Dr. Arvind Swaminathan (RWA Secretary)',
      photos: ['https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=800&q=80'],
    },
    inspection: {
      observedProblem: 'Heavy sand and concrete debris blockage inside 12-inch culvert pipe.',
      equipmentCondition: 'Cast iron frame intact; drainage flow blocked.',
      requiredWork: 'High-pressure water jet de-silting and manual rodding.',
      remarks: 'Initial attempt was surface-only. Mechanical rodding required.',
      inspectedAt: new Date(Date.now() - 32 * 3600 * 1000).toISOString(),
    },
    estimate: {
      items: [
        { rateCardId: 'RATE-02', service: 'General Labour (Semi-Skilled / Safety Assist)', unit: 'Hour', rate: 300, qty: 5, subtotal: 1500 },
      ],
      total: 1500,
      status: 'APPROVED',
    },
    rework: null,
  },
  {
    id: 'CMP-2026-0101',
    workOrderId: 'WO-2026-088',
    title: 'High-Mast Streetlight Failure at Main Sector 54 Junction',
    category: 'Electrical',
    subCategory: 'Streetlight Failure',
    location: {
      sector: 'Sector 54',
      block: 'Block B',
      street: 'Gulmohar Marg',
      assetId: 'ELE-HM-042',
      assetName: 'High-Mast Pole #42',
      landmark: 'Near Central Roundabout Fountain',
      gps: '28.5355° N, 77.3910° E',
    },
    severity: 'High',
    slaDeadline: new Date(Date.now() + 14 * 3600 * 1000).toISOString(),
    status: 'COMPLETED',
    description: 'High-mast LED cluster completely unlit since evening peak hours, creating severe hazard for evening commuter traffic.',
    reportedBy: { name: 'Dr. Arvind Swaminathan', role: 'RWA Secretary' },
    createdAt: new Date(Date.now() - 72 * 3600 * 1000).toISOString(),
    beforePhotos: ['https://images.unsplash.com/photo-1509114397022-ed747cca3f65?auto=format&fit=crop&w=800&q=80'],
    afterPhotos: ['https://images.unsplash.com/photo-1517457373958-b7bdd4587205?auto=format&fit=crop&w=800&q=80'],
    inspection: {
      observedProblem: 'Blown 150W driver and secondary surge arrester breakdown.',
      equipmentCondition: 'Driver burnt; wiring intact.',
      requiredWork: 'Install new 150W driver, fit miniature circuit breaker, re-align luminaires.',
      inspectionPhoto: 'https://images.unsplash.com/photo-1509114397022-ed747cca3f65?auto=format&fit=crop&w=800&q=80',
      remarks: 'Work order executed under AMC schedule.',
      inspectedAt: new Date(Date.now() - 60 * 3600 * 1000).toISOString(),
    },
    estimate: {
      items: [
        { rateCardId: 'RATE-01', service: 'Senior Electrical Technician / Wireman', unit: 'Hour', rate: 500, qty: 2, subtotal: 1000 },
        { rateCardId: 'RATE-02', service: 'General Labour (Semi-Skilled / Safety Assist)', unit: 'Hour', rate: 300, qty: 3, subtotal: 900 },
        { rateCardId: 'RATE-03', service: 'Armoured 3-Core Copper Cable 16 sq.mm', unit: 'Meter', rate: 150, qty: 10, subtotal: 1500 },
      ],
      total: 3400,
      status: 'APPROVED',
    },
    execution: {
      completedAt: new Date(Date.now() - 40 * 3600 * 1000).toISOString(),
      actualLabourDetails: 'Senior Technician Vikram Singh Rathore + 3 labour assistants.',
      actualWorkSummary: 'Replaced 150W industrial driver, installed new MCB protection and re-calibrated twilight timer. All 6 luminaires fully operational.',
      afterPhoto: 'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?auto=format&fit=crop&w=800&q=80',
    },
    rework: null,
  },
];
