// mockFinanceData.js - Realistic financial audit & invoice data for TIMS Finance Clerk
// Linked to INITIAL_CONTRACTORS and INITIAL_AMC_RATE_CARDS

export const INITIAL_INVOICES = [
  {
    id: 'INV-2026-088',
    invoiceNumber: 'VT-INV/2026/041',
    workOrderId: 'WO-2026-088',
    complaintId: 'CMP-2026-0101',
    title: 'High-Mast Streetlight Failure at Main Junction',
    department: 'Electrical',
    contractor: {
      id: 'cnt-02',
      name: 'Voltech Power & Lights',
      amcContractId: 'AMC-ELE-2025-03',
      accountNumber: 'HDFC0004928192831',
      gstin: '07AAAAA0000A1Z5',
    },
    estimateAmount: 3400,
    billedAmount: 3400,
    varianceAmount: 0,
    variancePercent: 0,
    auditStatus: 'PENDING_AUDIT', // PENDING_AUDIT | AUTHORIZED | VARIANCE_FLAGGED | PAID
    rateCardMatch: true,
    rwaVerified: true,
    submittedAt: new Date(Date.now() - 1 * 3600 * 1000).toISOString(),
    invoiceDueDate: new Date(Date.now() + 7 * 24 * 3600 * 1000).toISOString(),
    items: [
      {
        description: 'Electrician (Senior Technician)',
        unit: 'Hour',
        amcRate: 500,
        estimatedQty: 2,
        billedQty: 2,
        total: 1000,
        rateCardVerified: true,
      },
      {
        description: 'General Labour (Pole Climbing & Safety Assist)',
        unit: 'Hour',
        amcRate: 300,
        estimatedQty: 3,
        billedQty: 3,
        total: 900,
        rateCardVerified: true,
      },
      {
        description: 'Cable Work (High-flex insulated connection)',
        unit: 'Meter',
        amcRate: 150,
        estimatedQty: 10,
        billedQty: 10,
        total: 1500,
        rateCardVerified: true,
      },
    ],
    supportingDocs: [
      { name: 'Contractor_Measurement_Sheet_WO088.pdf', size: '240 KB' },
      { name: 'Signed_RWA_Inspection_Certificate.pdf', size: '180 KB' },
      { name: 'Before_After_Photographs_Compiled.pdf', size: '1.2 MB' },
    ],
    varianceReason: null,
    paymentBatchId: null,
    authorizedAt: null,
    authorizedBy: null,
  },
  {
    id: 'INV-2026-084',
    invoiceNumber: 'APX-CIV/2026/102',
    workOrderId: 'WO-2026-084',
    complaintId: 'CMP-2026-0094',
    title: 'Pothole Asphalt Filling & Edge Patching (Sector 2)',
    department: 'Civil',
    contractor: {
      id: 'cnt-01',
      name: 'Apex Infraworks Ltd.',
      amcContractId: 'AMC-CIV-2025-08',
      accountNumber: 'ICIC0009182371928',
      gstin: '07BBBBB1111B1Z2',
    },
    estimateAmount: 18000,
    billedAmount: 22800,
    varianceAmount: 4800,
    variancePercent: 26.6,
    auditStatus: 'VARIANCE_FLAGGED',
    rateCardMatch: false,
    rwaVerified: true,
    submittedAt: new Date(Date.now() - 14 * 3600 * 1000).toISOString(),
    invoiceDueDate: new Date(Date.now() + 5 * 24 * 3600 * 1000).toISOString(),
    items: [
      {
        description: 'Pothole Asphalt Filling',
        unit: 'Sq.Meter',
        amcRate: 1200,
        estimatedQty: 12,
        billedQty: 16,
        total: 19200,
        rateCardVerified: true,
      },
      {
        description: 'General Labour',
        unit: 'Hour',
        amcRate: 300,
        estimatedQty: 12,
        billedQty: 12,
        total: 3600,
        rateCardVerified: true,
      },
    ],
    supportingDocs: [
      { name: 'Site_Measurement_Log_Sec2.pdf', size: '420 KB' },
      { name: 'Bitumen_Mix_Challan_Batch_92.pdf', size: '150 KB' },
    ],
    varianceReason: 'Billed 16 sq.m asphalt filling vs. approved 12 sq.m estimate (+33% quantity increase without prior Dept Head addendum approval).',
    paymentBatchId: null,
    authorizedAt: null,
    authorizedBy: null,
  },
  {
    id: 'INV-2026-079',
    invoiceNumber: 'AQF-WTR/2026/019',
    workOrderId: 'WO-2026-079',
    complaintId: 'CMP-2026-0089',
    title: 'Sluice Valve Overhaul & Pipeline Junction Seal',
    department: 'Water',
    contractor: {
      id: 'cnt-03',
      name: 'AquaFlow Utilities Corp',
      amcContractId: 'AMC-WTR-2025-11',
      accountNumber: 'SBIN0001827364129',
      gstin: '07CCCCC2222C1Z8',
    },
    estimateAmount: 6600,
    billedAmount: 6600,
    varianceAmount: 0,
    variancePercent: 0,
    auditStatus: 'AUTHORIZED',
    rateCardMatch: true,
    rwaVerified: true,
    submittedAt: new Date(Date.now() - 48 * 3600 * 1000).toISOString(),
    invoiceDueDate: new Date(Date.now() + 2 * 24 * 3600 * 1000).toISOString(),
    items: [
      {
        description: 'Sluice Valve Overhaul',
        unit: 'Unit',
        amcRate: 2500,
        estimatedQty: 2,
        billedQty: 2,
        total: 5000,
        rateCardVerified: true,
      },
      {
        description: 'Pipe Repair & Fitting',
        unit: 'Unit',
        amcRate: 800,
        estimatedQty: 2,
        billedQty: 2,
        total: 1600,
        rateCardVerified: true,
      },
    ],
    supportingDocs: [
      { name: 'Pressure_Test_Certification_Pump4.pdf', size: '310 KB' },
      { name: 'AquaFlow_Final_Bill_019.pdf', size: '190 KB' },
    ],
    varianceReason: null,
    paymentBatchId: 'BATCH-2026-09-A',
    authorizedAt: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
    authorizedBy: 'Sunil Agrawal (Finance Clerk)',
  },
  {
    id: 'INV-2026-072',
    invoiceNumber: 'VT-INV/2026/033',
    workOrderId: 'WO-2026-072',
    complaintId: 'CMP-2026-0078',
    title: 'Feeder Pillar Replacement & MCB Rewiring (Sector 5)',
    department: 'Electrical',
    contractor: {
      id: 'cnt-02',
      name: 'Voltech Power & Lights',
      amcContractId: 'AMC-ELE-2025-03',
      accountNumber: 'HDFC0004928192831',
      gstin: '07AAAAA0000A1Z5',
    },
    estimateAmount: 14500,
    billedAmount: 14500,
    varianceAmount: 0,
    variancePercent: 0,
    auditStatus: 'PAID',
    rateCardMatch: true,
    rwaVerified: true,
    submittedAt: new Date(Date.now() - 96 * 3600 * 1000).toISOString(),
    invoiceDueDate: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    items: [
      {
        description: 'Streetlight LED Luminaire Replacement',
        unit: 'Unit',
        amcRate: 1800,
        estimatedQty: 5,
        billedQty: 5,
        total: 9000,
        rateCardVerified: true,
      },
      {
        description: 'Electrician',
        unit: 'Hour',
        amcRate: 500,
        estimatedQty: 7,
        billedQty: 7,
        total: 3500,
        rateCardVerified: true,
      },
      {
        description: 'General Labour',
        unit: 'Hour',
        amcRate: 300,
        estimatedQty: 6,
        billedQty: 6,
        total: 1800,
        rateCardVerified: true,
      },
      {
        description: 'Cable Work',
        unit: 'Meter',
        amcRate: 150,
        estimatedQty: 2,
        billedQty: 2,
        total: 200,
        rateCardVerified: true,
      },
    ],
    supportingDocs: [
      { name: 'Electrical_Inspector_Clearance.pdf', size: '480 KB' },
    ],
    varianceReason: null,
    paymentBatchId: 'BATCH-2026-08-D',
    authorizedAt: new Date(Date.now() - 72 * 3600 * 1000).toISOString(),
    authorizedBy: 'Sunil Agrawal (Finance Clerk)',
  },
]

export const INITIAL_DISBURSEMENTS = [
  {
    id: 'DISB-2026-0042',
    batchId: 'BATCH-2026-08-D',
    date: new Date(Date.now() - 48 * 3600 * 1000).toISOString(),
    contractorName: 'Voltech Power & Lights',
    department: 'Electrical',
    invoiceCount: 3,
    totalAmount: 42800,
    paymentMode: 'RTGS / Township Escrow',
    bankReference: 'UTR-HDFC-92819482910',
    status: 'DISBURSED',
  },
  {
    id: 'DISB-2026-0043',
    batchId: 'BATCH-2026-09-A',
    date: new Date(Date.now() + 24 * 3600 * 1000).toISOString(),
    contractorName: 'AquaFlow Utilities Corp',
    department: 'Water',
    invoiceCount: 2,
    totalAmount: 18400,
    paymentMode: 'NEFT Escrow',
    bankReference: 'UTR-PENDING-STAGE',
    status: 'SCHEDULED',
  },
]

export const DEPARTMENT_BUDGETS = {
  Civil: { allocated: 800000, spent: 485000, pending: 22800 },
  Electrical: { allocated: 650000, spent: 394000, pending: 3400 },
  Water: { allocated: 500000, spent: 280000, pending: 6600 },
}
