// mockFinanceData.js - Realistic financial audit & invoice data for TIMS Finance Clerk
// Location: DLF CyberCity & Aralias Smart Township, Sector 54, Gurugram (NCR), India
// 100% Constant & Synchronized with Database-react/seed.sql and backend-react

export const INITIAL_INVOICES = [
  {
    id: 'INV-2026-088',
    invoiceNumber: 'VT-INV/2026/041',
    workOrderId: 'WO-2026-088',
    complaintId: 'CMP-2026-0101',
    title: 'High-Mast Streetlight Failure at Main Sector 54 Junction',
    department: 'Electrical & Power Distribution',
    contractor: {
      id: 'c0000000-0000-0000-0000-000000000002',
      name: 'Voltech Power & Electrical Systems Ltd.',
      amcContractId: 'AMC-ELE-2025-03',
      accountNumber: 'ICIC0004321098765',
      gstin: '06AABCV5678G1Z4',
    },
    estimateAmount: 3400,
    billedAmount: 3400,
    varianceAmount: 0,
    variancePercent: 0,
    auditStatus: 'PAID',
    rateCardMatch: true,
    rwaVerified: true,
    submittedAt: new Date(Date.now() - 72 * 3600 * 1000).toISOString(),
    invoiceDueDate: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    items: [
      {
        description: 'Senior Electrical Technician / Wireman',
        unit: 'Hour',
        amcRate: 500,
        estimatedQty: 2,
        billedQty: 2,
        total: 1000,
        rateCardVerified: true,
      },
      {
        description: 'General Labour (Semi-Skilled / Safety Assist)',
        unit: 'Hour',
        amcRate: 300,
        estimatedQty: 3,
        billedQty: 3,
        total: 900,
        rateCardVerified: true,
      },
      {
        description: 'Armoured 3-Core Copper Cable 16 sq.mm',
        unit: 'Meter',
        amcRate: 150,
        estimatedQty: 10,
        billedQty: 10,
        total: 1500,
        rateCardVerified: true,
      },
    ],
    supportingDocs: [
      { name: 'Voltech_Measurement_Sheet_WO088.pdf', size: '240 KB' },
      { name: 'Signed_RWA_Inspection_Certificate.pdf', size: '180 KB' },
      { name: 'Before_After_Photographs_Compiled.pdf', size: '1.2 MB' },
    ],
    varianceReason: null,
    paymentBatchId: 'BATCH-2026-09-A',
    authorizedAt: new Date(Date.now() - 48 * 3600 * 1000).toISOString(),
    authorizedBy: 'Sunil Agrawal, CA (Finance Clerk)',
  },
  {
    id: 'INV-2026-079',
    invoiceNumber: 'KIRL-INV/2026/019',
    workOrderId: 'WO-2026-089',
    complaintId: 'CMP-2026-0102',
    title: '150mm DI Drinking Water Main Line Burst outside Tower 7',
    department: 'Water Supply & Drainage Sanitation',
    contractor: {
      id: 'c0000000-0000-0000-0000-000000000003',
      name: 'Kirloskar HydroTech & Water Systems Pvt. Ltd.',
      amcContractId: 'AMC-WTR-2025-11',
      accountNumber: 'SBIN0006789123456',
      gstin: '06AACKK9012H1Z1',
    },
    estimateAmount: 6600,
    billedAmount: 6600,
    varianceAmount: 0,
    variancePercent: 0,
    auditStatus: 'AUTHORIZED',
    rateCardMatch: true,
    rwaVerified: true,
    submittedAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    invoiceDueDate: new Date(Date.now() + 4 * 24 * 3600 * 1000).toISOString(),
    items: [
      {
        description: 'Heavy-Duty Cast Iron Sluice Valve Overhaul (150mm)',
        unit: 'Unit',
        amcRate: 2500,
        estimatedQty: 2,
        billedQty: 2,
        total: 5000,
        rateCardVerified: true,
      },
      {
        description: 'Pipe Repair & DI Pipeline Fitting (100mm/150mm)',
        unit: 'Unit',
        amcRate: 800,
        estimatedQty: 2,
        billedQty: 2,
        total: 1600,
        rateCardVerified: true,
      },
    ],
    supportingDocs: [
      { name: 'Hydrostatic_Pressure_Test_Certificate.pdf', size: '310 KB' },
      { name: 'Kirloskar_Final_Bill_019.pdf', size: '190 KB' },
    ],
    varianceReason: null,
    paymentBatchId: 'BATCH-2026-09-B',
    authorizedAt: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
    authorizedBy: 'Sunil Agrawal, CA (Finance Clerk)',
  },
  {
    id: 'INV-2026-084',
    invoiceNumber: 'LNT-INV/2026/102',
    workOrderId: 'WO-2026-091',
    complaintId: 'CMP-2026-0105',
    title: 'Stormwater Drain Silt Blockage & Monsoon Overflow near Market Complex',
    department: 'Civil Infrastructure & Roads',
    contractor: {
      id: 'c0000000-0000-0000-0000-000000000001',
      name: 'Larsen & Toubro Urban Infra Works Ltd.',
      amcContractId: 'AMC-CIV-2025-08',
      accountNumber: 'HDFC0001234987654',
      gstin: '06AAACL1234F1Z8',
    },
    estimateAmount: 18000,
    billedAmount: 22800,
    varianceAmount: 4800,
    variancePercent: 26.6,
    auditStatus: 'VARIANCE_FLAGGED',
    rateCardMatch: false,
    rwaVerified: true,
    submittedAt: new Date(Date.now() - 48 * 3600 * 1000).toISOString(),
    invoiceDueDate: new Date(Date.now() + 5 * 24 * 3600 * 1000).toISOString(),
    items: [
      {
        description: 'Bitumen Cold-Mix Asphalt Pothole Repair',
        unit: 'Sq.Meter',
        amcRate: 1200,
        estimatedQty: 12,
        billedQty: 16,
        total: 19200,
        rateCardVerified: true,
      },
      {
        description: 'General Labour (Semi-Skilled / Safety Assist)',
        unit: 'Hour',
        amcRate: 300,
        estimatedQty: 12,
        billedQty: 12,
        total: 3600,
        rateCardVerified: true,
      },
    ],
    supportingDocs: [
      { name: 'Site_Measurement_Log_Galleria.pdf', size: '420 KB' },
      { name: 'Bitumen_Mix_Challan_Batch_92.pdf', size: '150 KB' },
    ],
    varianceReason: 'Billed 16 sq.m asphalt filling vs. approved 12 sq.m estimate (+33% quantity increase without prior Dept Head addendum approval).',
    paymentBatchId: null,
    authorizedAt: null,
    authorizedBy: null,
  },
  {
    id: 'INV-2026-090',
    invoiceNumber: 'VT-INV/2026/055',
    workOrderId: 'WO-2026-090',
    complaintId: 'CMP-2026-0104',
    title: '11kV Transformer Substation Feeder Cable Ground Fault & Sparking',
    department: 'Electrical & Power Distribution',
    contractor: {
      id: 'c0000000-0000-0000-0000-000000000002',
      name: 'Voltech Power & Electrical Systems Ltd.',
      amcContractId: 'AMC-ELE-2025-03',
      accountNumber: 'ICIC0004321098765',
      gstin: '06AABCV5678G1Z4',
    },
    estimateAmount: 14200,
    billedAmount: 14200,
    varianceAmount: 0,
    variancePercent: 0,
    auditStatus: 'PENDING_AUDIT',
    rateCardMatch: true,
    rwaVerified: false,
    submittedAt: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
    invoiceDueDate: new Date(Date.now() + 7 * 24 * 3600 * 1000).toISOString(),
    items: [
      {
        description: 'Streetlight 120W LED Luminaire & Surge Driver Replacement',
        unit: 'Unit',
        amcRate: 1800,
        estimatedQty: 5,
        billedQty: 5,
        total: 9000,
        rateCardVerified: true,
      },
      {
        description: 'Senior Electrical Technician / Wireman',
        unit: 'Hour',
        amcRate: 500,
        estimatedQty: 7,
        billedQty: 7,
        total: 3500,
        rateCardVerified: true,
      },
      {
        description: 'General Labour (Semi-Skilled / Safety Assist)',
        unit: 'Hour',
        amcRate: 300,
        estimatedQty: 5,
        billedQty: 5,
        total: 1500,
        rateCardVerified: true,
      },
      {
        description: 'Armoured 3-Core Copper Cable 16 sq.mm',
        unit: 'Meter',
        amcRate: 150,
        estimatedQty: 1.33,
        billedQty: 1.33,
        total: 200,
        rateCardVerified: true,
      },
    ],
    supportingDocs: [
      { name: 'Electrical_Inspector_Clearance_Substation12B.pdf', size: '480 KB' },
    ],
    varianceReason: null,
    paymentBatchId: null,
    authorizedAt: null,
    authorizedBy: null,
  },
];

export const INITIAL_DISBURSEMENTS = [
  {
    id: 'DISB-2026-0042',
    batchId: 'BATCH-2026-09-A',
    date: new Date(Date.now() - 48 * 3600 * 1000).toISOString(),
    contractorName: 'Voltech Power & Electrical Systems Ltd.',
    department: 'Electrical & Power Distribution',
    invoiceCount: 1,
    totalAmount: 3400,
    paymentMode: 'RTGS / Township Escrow',
    bankReference: 'UTR-HDFC-9928192831',
    status: 'DISBURSED',
  },
  {
    id: 'DISB-2026-0043',
    batchId: 'BATCH-2026-09-B',
    date: new Date(Date.now() + 24 * 3600 * 1000).toISOString(),
    contractorName: 'Kirloskar HydroTech & Water Systems Pvt. Ltd.',
    department: 'Water Supply & Drainage Sanitation',
    invoiceCount: 1,
    totalAmount: 6600,
    paymentMode: 'NEFT Escrow',
    bankReference: 'UTR-PENDING-STAGE',
    status: 'SCHEDULED',
  },
];

export const DEPARTMENT_BUDGETS = {
  Civil: { allocated: 1500000, spent: 485000, pending: 22800 },
  Electrical: { allocated: 1200000, spent: 394000, pending: 14200 },
  Water: { allocated: 900000, spent: 280000, pending: 6600 },
  Horticulture: { allocated: 400000, spent: 120000, pending: 0 },
};
